---
- name: web_dep 자동 배포 플레이북
  hosts: web
  become: true
  vars:
    git_repo_url: "https://github.com/illgod0228/ANSIBLE-TEST.git"
    web_root: "/var/www/html"

  tasks:
    - name: Nginx 웹 서버 설치
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: 기존 기본 파일 삭제
      file:
        path: "{{ web_root }}/index.nginx-debian.html"
        state: absent

    - name: GitHub 저장소에서 최신 소스 코드 배포
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ web_root }}"
        version: main
        force: yes

    - name: Nginx 서비스 활성화 및 시작
      service:
        name: nginx
        state: started
        enabled: true

